### ISSUE TITLE
error while retrieving xml: : Unauthorized (HTTP 401).

### ISSUE THREAD

**Issue by RinaGF** [christopherBelter/scopusAPI#2]
I was using:

theXML <- searchByString (string = query, outfile = "testdata.xml")

then i get an error:

Error in searchByString (string = query, outfile = "testdata.xml"): Unauthorized (HTTP 401).
3. stop (http_condition (x, "error", task = task, call = call))
2. httr :: stop_for_status (theURL) at scopusAPI.R # 12
1. searchByString (string = query, outfile = "testdata.xml")

I'm new to R, was it my API key that create error Unauthorized (HTTP 401)?

**Comment by christopherBelter** [comment]
Hi, 

It looks like your API key is the issue here. According to the Scopus Search API documentation (https://dev.elsevier.com/documentation/ScopusSearchAPI.wadl), HTTP 401 errors are caused "when a user cannot be authenticated due to missing/invalid credentials (authtoken or APIKey)", so what probably happened is that your API key wasn't put into the .R file correctly.

So try double-checking that you put the correct API key in line 9 of the .R file (key <- "yourAPIKey"), replacing the "yourAPIKey" text with your actual API key, and trying again. You'll also want to check line 52 as well to make sure the searchByID() function works properly, too. 

If you're sure you have the right API key in there, then most likely something is wrong with the key itself, so you'll want to contact Elsevier through the development portal to see if the API key works properly. But, I'm pretty sure the problem is caused by a missing or invalid API key in the .R file itself.

Chris

**Comment by christopherBelter** [comment]
For the record, authentication errors can also be caused by attempting to access the full Scopus API from a non-authenticated IP address. So if your institution uses IP authentication to provide access to Scopus, you have to make the API request from an authenticated IP address. In practice, this means using a computer on your institution's network or logging in to your institution's VPN before trying to use the API functions.
